### ISSUE TITLE
Error in wb$workbook$sheets[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by hk20013106** [gwangjinkim/xlsx2dfs#1]
I want to report a very weird thing (I don't even know whether this is a bug). I generate xlsx files with multiple sheets using **write.xlsx** function. 

When import  the xlsx using xlsx2df2, it says   **"Error in wb$workbook$sheets[[i]] : subscript out of bounds"**

I manually edit the xlsx, to include a new sheet, and delete the new sheet, and save it in Microsoft excel. Then I use **xlsx2dfs** to import the xlsx file.  It works. 

I'm doing this under Windows 10, Rstudio 1.3.959

sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 20152)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 936

**Comment by gwangjinkim** [comment]
thank you for reporting.
Could you show me a reproducible example? (the best is even with excel file which you read-in but which can't be written out.
Did you read the vignette carefully? You use `dfs2xlsx()` for writing out a list of data frames.

**Comment by gwangjinkim** [comment]
The error message is actually from `openxlsx` package - which is the underlying package of `xlsx2dfs`.

**Comment by gwangjinkim** [comment]
Using this package, you should use the `dfs2xlsx()` function to write out a list of data frames (the names of the list elements will be the sheet names). If you use `write.xlsx()` function, then you are using actually the underlying `openxlsx` functionalities - which is not intended to be used using this package. Please read the vignette for this package (xlsx2dfs) carefully and try the examples.

**Comment by hk20013106** [comment]
Thank you very much for your quick reply. I was trying to include xlsx2dfs into an existing pipeline and didn't realize that xlsx files generated using write.xlsx could be incompatible. I'm trying to include dfs2xlsx in the pipeline, and realize that it is not compatible with non-common characters. 


I have a list of data.frame call "maker_list", it has 12 df. 
The sheet  names are like: "Cd34_match>dn_match"     "Cd34_match>dp_match" 


The following do not work. 
dfs2xlsx(withNames("Cd34_match>dn_match", marker_list[[1]],"Cd34_match>dp_match",marker_list[[2]]),"test3.xlsx")
#Error: Sheet 'Cd34_match>dn_match' does not exist.

dfs2xlsx(marker_list,"test4.xlsx")
#Error: Sheet 'Cd34_match>dn_match' does not exist.


remove the ">" in the sheet name solve the problem.
dfs2xlsx(withNames("Cd34_match dn_match", marker_list[[1]],"Cd34_match dp_match",marker_list[[2]]),"test3.xlsx")
#done

**Comment by gwangjinkim** [comment]
The ">" is simply also not allowed in Excel sheet names.
Only `[a-zA-Z0-9 _.]` (alphanumeric + empty space + underscore ('_') + period ('.')) are allowed in excel sheet names.
See [here](http://www.excelcodex.com/2012/06/worksheets-naming-conventions/).

So again, this is a problem of Excel sheets, not of this package.

But thank you for pointing this point out!!
